# Generated by Django 5.1.1 on 2024-09-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved')], default='approved', max_length=10),
        ),
    ]
