# Generated by Django 5.1.3 on 2024-11-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('notes', '0003_alter_note_options_note_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['topic'], name='notes_note_topic_9e51e1_idx'),
        ),
    ]
