# Generated by Django 5.1.1 on 2024-09-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='content',
            field=models.TextField(default='no content given'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='note',
            field=models.TextField(default='No notes available'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
