# Generated by Django 5.1.3 on 2024-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_remove_question_option_a_remove_question_option_b_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='notes_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
