# Generated by Django 5.1.3 on 2024-11-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quiz_options_quiz_notes_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='notes_content',
        ),
    ]
