# Generated by Django 5.1.3 on 2024-11-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_quiz_options_remove_quiz_notes_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='note_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
