# Generated by Django 5.1.3 on 2024-11-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quiz_note_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='note_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
